# This is a basic workflow to help you get started with Actions

name: 🚀 Deploy website on push with FTP

on:
  push:
    branches:
      - dev

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          # ftp server
          server: ${{ secrets.vp_ftp_server }}
          # ftp username
          username: ${{ secrets.vp_ftp_username }}
          # ftp password
          password: ${{ secrets.vp_ftp_password }}
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /php-web-server.langnang-dev.ml/htdocs/
